# Generated by Django 3.2.2 on 2021-05-14 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.post'),
        ),
    ]
