# Generated by Django 3.2.2 on 2021-05-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_like_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
        migrations.AlterField(
            model_name='like',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog_app.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
